name: Source Code Check
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9
          environment-file: environment.yml
          activate-environment: ds
      - name: Test
        shell: bash -l {0}
        run: pre-commit run --all-files
